import streamlit as st
import sqlite3
import re

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="BD PC Builder", 
    page_icon="🖥️", 
    layout="wide", # Switched to Wide mode for better builder layout
    initial_sidebar_state="collapsed"
)

# --- DATABASE CONNECTION ---
def get_db_connection():
    try:
        conn = sqlite3.connect('tech_data.db')
        conn.row_factory = sqlite3.Row
        return conn
    except Exception as e:
        st.error(f"Database Error: {e}")
        return None

# --- HELPER: WATTAGE PARSER ---
def get_wattage(name):
    match = re.search(r'(\d{3,4})\s*[Ww]', name) 
    if match: return int(match.group(1))
    return 0 

# --- HELPER: CPU LOGIC (MANDATORY GPU CHECK) ---
def is_gpu_mandatory(cpu_name):
    """Returns True if the CPU has NO integrated graphics"""
    name = cpu_name.upper()
    # Intel F or KF series (e.g., i5-12400F, i9-13900KF) -> Needs GPU
    if "INTEL" in name and ("F" in name.split() or "KF" in name): 
        return True
    
    # AMD Logic:
    # Ryzen 5000 series (non-G) usually need GPU. 
    # Ryzen 7000/8000/9000 usually HAVE iGPU (but weak).
    # For safety, we only force GPU on known "No iGPU" chips if we can detect them.
    # Simple Rule: If it's AMD and NOT 'G' series (APU), we highly recommend GPU, 
    # but strictly speaking, only old Ryzens blocked booting.
    # Let's stick to the strict Intel rule for now to avoid false positives.
    return False

# --- HELPER: DETAILED POWER CALCULATOR ---
def calculate_power_breakdown(parts):
    breakdown = { "Base System": 100, "CPU": 0, "GPU": 0, "Storage": 0, "Total": 0 }
    
    if 'CPU' in parts:
        name = parts['CPU']['name'].upper()
        watts = 100 
        if "I9" in name or "RYZEN 9" in name: watts = 300
        elif "I7" in name or "RYZEN 7" in name: watts = 250
        elif "I5" in name or "RYZEN 5" in name: watts = 150
        breakdown["CPU"] = watts
        
    if 'Graphics Card' in parts:
        name = parts['Graphics Card']['name'].upper()
        watts = 150 
        if "4090" in name: watts = 500
        elif "4080" in name: watts = 350
        elif "7900" in name: watts = 360
        elif "4070" in name: watts = 300 if ("TI" in name or "SUPER" in name) else 240
        elif "7800" in name or "6900" in name: watts = 300
        elif "3080" in name: watts = 350
        elif "4060" in name or "3060" in name: watts = 180
        elif "7700" in name or "6700" in name: watts = 260
        elif "3050" in name or "6600" in name: watts = 140
        breakdown["GPU"] = watts

    if 'Storage' in parts: breakdown["Storage"] = 15
    breakdown["Total"] = sum(breakdown.values())
    return breakdown

# --- HELPER: TEXT SUMMARY ---
def generate_build_summary(parts, total, watts):
    text = "🖥️ My PC Build List\n"
    text += f"💰 Total: {total} Tk | ⚡ Power: {watts}W\n\n"
    for part_type, item in parts.items():
        text += f"* {part_type}: {item['name']} ({item['price']} Tk)\n"
    text += "\n🚀 Generated by BD PC Builder AI"
    return text

# --- HELPER: DATABASE FETCHERS ---
def get_best_item(cursor, table, max_price, spec_constraint=None, min_watts=0):
    query = f"SELECT * FROM {table} WHERE price <= ? AND price > 0"
    params = [max_price]
    if spec_constraint:
        query += " AND spec_tag LIKE ?"
        params.append(f"%{spec_constraint}%")
    query += " ORDER BY price DESC"
    cursor.execute(query, params)
    rows = cursor.fetchall()
    if min_watts > 0 and table == 'psus':
        valid_psus = [row for row in rows if get_wattage(row['name']) >= min_watts]
        return valid_psus[0] if valid_psus else None
    return rows[0] if rows else None

def get_cheapest_item(cursor, table, min_watts=0):
    cursor.execute(f"SELECT * FROM {table} WHERE price > 0 ORDER BY price ASC")
    rows = cursor.fetchall()
    if min_watts > 0 and table == 'psus':
        valid_psus = [row for row in rows if get_wattage(row['name']) >= min_watts]
        return valid_psus[0] if valid_psus else None
    return rows[0] if rows else None

# --- SWAP HELPER ---
def get_alternatives(table, current_price, name_search=None):
    conn = get_db_connection()
    if not conn: return []
    cursor = conn.cursor()
    min_price = current_price * 0.5
    max_price = current_price * 3.0
    query = f"SELECT * FROM {table} WHERE price BETWEEN ? AND ?"
    params = [min_price, max_price]
    if name_search:
        query += " AND name LIKE ?"
        params.append(f"%{name_search}%")
    query += " ORDER BY price DESC LIMIT 50" 
    cursor.execute(query, params)
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]

# --- HOVER BADGE ---
def render_power_badge(breakdown):
    css = """<style>.power-container { position: relative; display: inline-block; cursor: pointer; font-family: sans-serif; } .power-badge { background-color: #FF4B4B; color: white; padding: 8px 16px; border-radius: 8px; font-weight: bold; font-size: 18px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); transition: transform 0.2s; } .power-badge:hover { transform: scale(1.05); } .power-tooltip { visibility: hidden; width: 220px; background-color: #262730; color: #fff; text-align: left; border-radius: 8px; padding: 12px; position: absolute; z-index: 10; top: 125%; left: 50%; margin-left: -110px; box-shadow: 0 8px 16px rgba(0,0,0,0.2); opacity: 0; transition: opacity 0.3s; border: 1px solid #444; } .power-container:hover .power-tooltip { visibility: visible; opacity: 1; } .power-row { display: flex; justify-content: space-between; margin-bottom: 4px; font-size: 14px; } .power-total { border-top: 1px solid #666; padding-top: 8px; margin-top: 8px; font-weight: bold; color: #FF4B4B; }</style>"""
    html = f"""{css}<div class="power-container"><div class="power-badge">⚡ {breakdown['Total']}W</div><div class="power-tooltip"><div class="power-row"><span>System Base:</span> <span>{breakdown['Base System']}W</span></div><div class="power-row"><span>CPU Max:</span> <span>{breakdown['CPU']}W</span></div><div class="power-row"><span>GPU Peak:</span> <span>{breakdown['GPU']}W</span></div><div class="power-row"><span>Storage:</span> <span>{breakdown['Storage']}W</span></div><div class="power-row power-total"><span>EST. PEAK:</span> <span>{breakdown['Total']}W</span></div></div></div>"""
    return html

# --- SHARE MENU ---
@st.dialog("📤 Share Your Build")
def show_share_menu(link):
    st.write("Choose a platform:")
    st.text_input("Copy Link:", value=link)
    col1, col2 = st.columns(2)
    col3, col4 = st.columns(2)
    btn_style = """<style>.share-btn { display: inline-block; text-decoration: none; color: white !important; width: 100%; padding: 10px; text-align: center; border-radius: 8px; font-weight: bold; margin-bottom: 10px; }</style>"""
    st.markdown(btn_style, unsafe_allow_html=True)
    with col1: st.markdown(f'<a href="https://www.facebook.com/sharer/sharer.php?u={link}" target="_blank" class="share-btn" style="background-color: #1877F2;">📘 Facebook</a>', unsafe_allow_html=True)
    with col2: st.markdown(f'<a href="https://api.whatsapp.com/send?text=Check%20out%20this%20PC:%20{link}" target="_blank" class="share-btn" style="background-color: #25D366;">💬 WhatsApp</a>', unsafe_allow_html=True)
    with col3: st.markdown(f'<a href="fb-messenger://share/?link={link}" target="_blank" class="share-btn" style="background-color: #0084FF;">⚡ Messenger</a>', unsafe_allow_html=True)
    with col4: st.markdown(f'<a href="mailto:?subject=My PC Build&body=Check out this build: {link}" class="share-btn" style="background-color: #555;">✉️ Email</a>', unsafe_allow_html=True)

# --- MASTER BUILD LOGIC ---
def generate_pc_build(budget, include_gpu=True):
    conn = get_db_connection()
    if not conn: return None, 0, 0, 0
    cursor = conn.cursor()
    remaining = budget
    parts = {}
    
    # Phase 1: Core
    cpu = get_best_item(cursor, "processors", budget * 0.30) or get_cheapest_item(cursor, "processors")
    if cpu: 
        remaining -= cpu['price']
        parts['CPU'] = dict(cpu)
        
        cpu_name = cpu['name'].upper()
        if "INTEL" in cpu_name: cpu_type = "Intel"
        elif "AMD" in cpu_name: cpu_type = "AMD"
        else: cpu_type = None

        # Check GPU Requirement
        gpu_required = is_gpu_mandatory(cpu['name'])
        
        # 2. Motherboard
        mobo_budget = budget * 0.20
        mobo = None
        if cpu_type: mobo = get_best_item(cursor, "motherboards", mobo_budget, cpu_type)
        if not mobo: mobo = get_best_item(cursor, "motherboards", mobo_budget) or get_cheapest_item(cursor, "motherboards")
            
        if mobo:
            remaining -= mobo['price']
            parts['Motherboard'] = dict(mobo)
            mobo_name = mobo['name'].upper()
            ram_type = "DDR4"
            if "DDR5" in mobo_name or " D5 " in mobo_name or any(x in mobo_name for x in ["X670", "B650", "AM5", "Z790", "A620"]):
                if "D4" not in mobo_name: ram_type = "DDR5"
            ram = get_best_item(cursor, "rams", budget * 0.10, ram_type) or get_best_item(cursor, "rams", budget * 0.10, "DDR4") or get_cheapest_item(cursor, "rams")
            if ram: remaining -= ram['price']; parts['RAM'] = dict(ram)
    
    ssd = get_best_item(cursor, "ssds", budget * 0.10) or get_cheapest_item(cursor, "ssds")
    if ssd: remaining -= ssd['price']; parts['Storage'] = dict(ssd)
    casing = get_best_item(cursor, "casings", 5000) or get_cheapest_item(cursor, "casings")
    if casing: remaining -= casing['price']; parts['Casing'] = dict(casing)

    # Phase 2: Reserve & GPU
    # If GPU is NOT included and NOT required, we skip reserving money for it
    if include_gpu or gpu_required:
        if budget < 60000: psu_reserve = 3500 
        elif budget < 100000: psu_reserve = 5000 
        else: psu_reserve = budget * 0.10

        gpu = None
        gpu_budget = remaining - psu_reserve 
        if gpu_budget > 10000:
            gpu = get_best_item(cursor, "gpus", gpu_budget)
            if gpu: remaining -= gpu['price']; parts['Graphics Card'] = dict(gpu)
    
    # Phase 3: Safety & PSU
    breakdown_data = calculate_power_breakdown(parts) 
    estimated_watts = breakdown_data['Total']
    recommended_psu_watts = estimated_watts + 150 
    
    psu = get_best_item(cursor, "psus", remaining, min_watts=recommended_psu_watts)
    if not psu: psu = get_cheapest_item(cursor, "psus", min_watts=recommended_psu_watts)
    if not psu: psu = get_best_item(cursor, "psus", remaining) 
    if psu: remaining -= psu['price']; parts['Power Supply'] = dict(psu)

    # Phase 4: Sweeper (Only if GPU is included/required)
    if include_gpu or gpu_required:
        upgrade_order = [('Graphics Card', 'gpus', None), ('CPU', 'processors', None), ('RAM', 'rams', ram_type), ('Storage', 'ssds', None), ('Motherboard', 'motherboards', cpu_type)]
        for part_name, table, constraint in upgrade_order:
            if part_name in parts and remaining > 1000:
                current_item = parts[part_name]
                current_price = current_item['price']
                potential_budget = current_price + remaining
                better_item = get_best_item(cursor, table, potential_budget, constraint)
                if better_item and better_item['price'] > current_price:
                    cost_diff = better_item['price'] - current_price
                    parts[part_name] = dict(better_item)
                    remaining -= cost_diff

    final_breakdown = calculate_power_breakdown(parts)
    conn.close()
    return parts, sum(p['price'] for p in parts.values()), remaining, final_breakdown, gpu_required

# --- UI START ---
st.title("🖥️ BD PC Builder AI v7.0")
st.caption("Smart Configurator. GPU Logic. Optimized Budget.")

query_params = st.query_params
safe_budget = 40000
if "budget" in query_params:
    try: safe_budget = int(query_params["budget"])
    except: pass

# --- INPUT SECTION ---
col1, col2 = st.columns([2, 1])
with col1:
    budget_input = st.number_input("💰 Budget (BDT)", min_value=15000, max_value=800000, step=1000, value=safe_budget, key="budget_v7")
with col2:
    st.write("") # Spacer
    st.write("")
    include_gpu_check = st.checkbox("Include Graphics Card?", value=True, help="Uncheck if you want to use Integrated Graphics (if available).")

if "build_results" not in st.session_state: st.session_state.build_results = None

if st.button("🚀 Build PC", type="primary", use_container_width=True):
    st.query_params["budget"] = budget_input
    # We pass the checkbox preference, but the function might OVERRIDE it if CPU requires GPU
    parts, total_cost, saved, watts, gpu_forced = generate_pc_build(budget_input, include_gpu_check)
    
    # Check if GPU was forced
    gpu_msg = None
    if gpu_forced and not include_gpu_check:
        gpu_msg = "⚠️ GPU was added automatically because the selected CPU has no Integrated Graphics."
        
    st.session_state.build_results = {"parts": parts, "total": total_cost, "saved": saved, "watts": watts, "gpu_msg": gpu_msg}

if st.session_state.build_results:
    data = st.session_state.build_results
    parts = data["parts"]
    current_total = sum(p['price'] for p in parts.values())
    current_breakdown = calculate_power_breakdown(parts)
    
    if parts:
        st.divider()
        if data.get("gpu_msg"):
            st.warning(data["gpu_msg"])
            
        col_res1, col_res2, col_res3 = st.columns([2, 1, 1])
        with col_res1:
            st.success(f"✅ Total: **{current_total} BDT**")
        with col_res2:
             share_url = f"https://bd-pc-builder.streamlit.app/?budget={budget_input}"
             if st.button("📤 Share", use_container_width=True): show_share_menu(share_url)  
        with col_res3:
            badge_html = render_power_badge(current_breakdown)
            st.markdown(badge_html, unsafe_allow_html=True)
            
        with st.expander("📋 View & Copy Parts List"):
            summary_text = generate_build_summary(parts, current_total, current_breakdown['Total'])
            st.code(summary_text, language="text")

        st.divider()

        # --- SEPARATE REQUIRED VS OPTIONAL ---
        st.subheader("🛠️ Core Components")
        
        table_map = {
            'CPU': 'processors', 'Motherboard': 'motherboards', 'RAM': 'rams',
            'Storage': 'ssds', 'Graphics Card': 'gpus', 'Power Supply': 'psus', 'Casing': 'casings'
        }

        # Core Loop
        core_items = {k: v for k, v in parts.items() if k != 'Graphics Card'}
        gpu_item = parts.get('Graphics Card')

        for part_type, item in core_items.items():
            with st.container():
                col_img, col_details, col_price, col_action = st.columns([1, 2, 1, 0.5])
                with col_img:
                    if item.get('image_url'): st.image(item['image_url'], width=80)
                    else: st.write("📦")
                with col_details:
                    st.markdown(f"**{part_type}**")
                    st.caption(item['name'])
                    if part_type == "Power Supply":
                         watts = get_wattage(item['name'])
                         if watts > 0: st.caption(f"⚡ Capacity: {watts}W")
                with col_price:
                    st.markdown(f"**{item['price']} ৳**")
                    if item.get('url'): st.link_button("🛒", f"{item['url']}?ref=YOUR_ID")
                with col_action:
                     # Swap Logic (Same as before)
                    constraint = None
                    if part_type == 'CPU': 
                        if "INTEL" in item['name'].upper(): constraint = "Intel"
                        elif "AMD" in item['name'].upper() or "RYZEN" in item['name'].upper(): constraint = "AMD"
                    elif part_type == 'Motherboard':
                        cpu_name = parts['CPU']['name'].upper()
                        if "INTEL" in cpu_name: constraint = "Intel"
                        elif "AMD" in cpu_name or "RYZEN" in cpu_name: constraint = "AMD" 
                    elif part_type == 'RAM':
                        constraint = "DDR5" if "DDR5" in parts['Motherboard']['name'].upper() else "DDR4"
                    
                    with st.popover("🔄"):
                        st.markdown(f"**Swap {part_type}**")
                        table_name = table_map.get(part_type)
                        if table_name:
                            alts = get_alternatives(table_name, item['price'], constraint)
                            alts.insert(0, item) 
                            seen = set()
                            unique_alts = []
                            for a in alts:
                                if a['name'] not in seen:
                                    unique_alts.append(a)
                                    seen.add(a['name'])

                            if unique_alts:
                                alt_map = {f"{a['name'][:40]}... ({a['price']} ৳)": a for a in unique_alts}
                                selected_name = st.selectbox("Choose:", list(alt_map.keys()), index=0, key=f"sel_{part_type}")
                                if st.button("Confirm", key=f"btn_{part_type}"):
                                    st.session_state.build_results['parts'][part_type] = alt_map[selected_name]
                                    st.rerun()

        # GPU Section (Separate)
        if gpu_item:
            st.subheader("🎮 Graphics & Expansion")
            with st.container():
                col_img, col_details, col_price, col_action = st.columns([1, 2, 1, 0.5])
                with col_img:
                    if gpu_item.get('image_url'): st.image(gpu_item['image_url'], width=80)
                    else: st.write("📦")
                with col_details:
                    st.markdown("**Graphics Card**")
                    st.caption(gpu_item['name'])
                with col_price:
                    st.markdown(f"**{gpu_item['price']} ৳**")
                    if gpu_item.get('url'): st.link_button("🛒", f"{gpu_item['url']}?ref=YOUR_ID")
                with col_action:
                    with st.popover("🔄"):
                        st.markdown("**Swap GPU**")
                        alts = get_alternatives("gpus", gpu_item['price'])
                        alts.insert(0, gpu_item)
                        # ... (Same deduplication logic)
                        seen = set()
                        unique_alts = []
                        for a in alts:
                            if a['name'] not in seen: unique_alts.append(a); seen.add(a['name'])
                        
                        alt_map = {f"{a['name'][:40]}... ({a['price']} ৳)": a for a in unique_alts}
                        selected_name = st.selectbox("Choose:", list(alt_map.keys()), index=0, key="sel_gpu")
                        if st.button("Confirm", key="btn_gpu"):
                            st.session_state.build_results['parts']['Graphics Card'] = alt_map[selected_name]
                            st.rerun()

                st.divider()

        # Budget Feedback
        live_unused = budget_input - current_total
        if live_unused > 20000:
            st.info(f"💎 **Surplus Budget: {live_unused} BDT**\n\nYou have purchased the best available components! Use this extra cash for a Monitor, Keyboard, or specialized cooling.")
        elif live_unused > 0:
            st.warning(f"💵 Unused Budget: {live_unused} BDT")
        elif live_unused < 0:
            st.error(f"⚠️ Over Budget: {abs(live_unused)} BDT")