import streamlit as st
import sqlite3
import re

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="BD PC Builder", 
    page_icon="🖥️", 
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- DATABASE CONNECTION ---
def get_db_connection():
    try:
        conn = sqlite3.connect('tech_data.db')
        conn.row_factory = sqlite3.Row
        return conn
    except Exception as e:
        st.error(f"Database Error: {e}")
        return None

# --- HELPER: GET ALL CPUS ---
def get_all_cpus():
    conn = get_db_connection()
    if not conn: return []
    cursor = conn.cursor()
    cursor.execute("SELECT name, price FROM processors ORDER BY price DESC")
    rows = cursor.fetchall()
    conn.close()
    return [f"{row['name']} ({row['price']} ৳)" for row in rows]

# --- HELPER: CPU PARSER ---
def get_cpu_object(selection_string):
    if not selection_string: return None
    name = selection_string.rsplit(' (', 1)[0]
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM processors WHERE name = ?", (name,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None

# --- HELPER: WATTAGE PARSER ---
def get_wattage(name):
    match = re.search(r'(\d{3,4})\s*[Ww]', name) 
    if match: return int(match.group(1))
    return 0 

# --- HELPER: MANDATORY GPU CHECK ---
def is_gpu_mandatory(cpu_name):
    name = cpu_name.upper()
    if "INTEL" in name and ("F" in name.split() or "KF" in name): return True
    if "RYZEN" in name and "5" in name and "G" not in name and "7000" not in name and "8000" not in name and "9000" not in name:
         return True
    return False

# --- HELPER: BOTTLENECK CALCULATOR ---
def check_bottleneck(cpu_price, gpu_price):
    if gpu_price == 0: return None
    ratio = gpu_price / cpu_price
    if ratio < 0.4:
        return "⚠️ **Bottleneck:** GPU is too weak for this CPU."
    return None

# --- HELPER: POWER BREAKDOWN ---
def calculate_power_breakdown(parts):
    breakdown = { "Base System": 100, "CPU": 0, "GPU": 0, "Storage": 0, "Total": 0 }
    if 'CPU' in parts:
        name = parts['CPU']['name'].upper()
        watts = 100 
        if "I9" in name or "RYZEN 9" in name: watts = 300
        elif "I7" in name or "RYZEN 7" in name: watts = 250
        elif "I5" in name or "RYZEN 5" in name: watts = 150
        breakdown["CPU"] = watts
    if 'Graphics Card' in parts:
        name = parts['Graphics Card']['name'].upper()
        watts = 150 
        if "4090" in name: watts = 500
        elif "4080" in name: watts = 350
        elif "7900" in name: watts = 360
        elif "4070" in name: watts = 300 if ("TI" in name or "SUPER" in name) else 240
        elif "7800" in name or "6900" in name: watts = 300
        elif "3080" in name: watts = 350
        elif "4060" in name or "3060" in name: watts = 180
        elif "7700" in name or "6700" in name: watts = 260
        elif "3050" in name or "6600" in name: watts = 140
        breakdown["GPU"] = watts
    if 'Storage' in parts: breakdown["Storage"] = 15
    breakdown["Total"] = sum(breakdown.values())
    return breakdown

# --- HELPER: GENERATE SUMMARY TEXT ---
def generate_build_summary(parts, total, watts):
    text = "🖥️ My PC Build List\n"
    text += f"💰 Total: {total} Tk | ⚡ Power: {watts}W\n\n"
    for part_type, item in parts.items():
        text += f"* {part_type}: {item['name']} ({item['price']} Tk)\n"
    text += "\n🚀 Generated by BD PC Builder AI"
    return text

# --- DATABASE FETCHERS ---
def get_best_item(cursor, table, max_price, spec_constraint=None, min_watts=0):
    query = f"SELECT * FROM {table} WHERE price <= ? AND price > 0"
    params = [max_price]
    if spec_constraint:
        query += " AND spec_tag LIKE ?"
        params.append(f"%{spec_constraint}%")
    query += " ORDER BY price DESC"
    cursor.execute(query, params)
    rows = cursor.fetchall()
    if min_watts > 0 and table == 'psus':
        valid_psus = [row for row in rows if get_wattage(row['name']) >= min_watts]
        return valid_psus[0] if valid_psus else None
    return rows[0] if rows else None

def get_cheapest_item(cursor, table, min_watts=0):
    cursor.execute(f"SELECT * FROM {table} WHERE price > 0 ORDER BY price ASC")
    rows = cursor.fetchall()
    if min_watts > 0 and table == 'psus':
        valid_psus = [row for row in rows if get_wattage(row['name']) >= min_watts]
        return valid_psus[0] if valid_psus else None
    return rows[0] if rows else None

# --- SWAP HELPER ---
def get_alternatives(table, current_price, name_search=None):
    conn = get_db_connection()
    if not conn: return []
    cursor = conn.cursor()
    min_price = current_price * 0.5
    max_price = current_price * 3.0
    query = f"SELECT * FROM {table} WHERE price BETWEEN ? AND ?"
    params = [min_price, max_price]
    if name_search:
        query += " AND name LIKE ?"
        params.append(f"%{name_search}%")
    query += " ORDER BY price DESC LIMIT 50" 
    cursor.execute(query, params)
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]

# --- HOVER BADGE ---
def render_power_badge(breakdown):
    css = """<style>.power-container { position: relative; display: inline-block; cursor: pointer; font-family: sans-serif; } .power-badge { background-color: #FF4B4B; color: white; padding: 8px 16px; border-radius: 8px; font-weight: bold; font-size: 18px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); transition: transform 0.2s; } .power-badge:hover { transform: scale(1.05); } .power-tooltip { visibility: hidden; width: 220px; background-color: #262730; color: #fff; text-align: left; border-radius: 8px; padding: 12px; position: absolute; z-index: 10; top: 125%; left: 50%; margin-left: -110px; box-shadow: 0 8px 16px rgba(0,0,0,0.2); opacity: 0; transition: opacity 0.3s; border: 1px solid #444; } .power-container:hover .power-tooltip { visibility: visible; opacity: 1; } .power-row { display: flex; justify-content: space-between; margin-bottom: 4px; font-size: 14px; } .power-total { border-top: 1px solid #666; padding-top: 8px; margin-top: 8px; font-weight: bold; color: #FF4B4B; }</style>"""
    html = f"""{css}<div class="power-container"><div class="power-badge">⚡ {breakdown['Total']}W</div><div class="power-tooltip"><div class="power-row"><span>System Base:</span> <span>{breakdown['Base System']}W</span></div><div class="power-row"><span>CPU Max:</span> <span>{breakdown['CPU']}W</span></div><div class="power-row"><span>GPU Peak:</span> <span>{breakdown['GPU']}W</span></div><div class="power-row"><span>Storage:</span> <span>{breakdown['Storage']}W</span></div><div class="power-row power-total"><span>EST. PEAK:</span> <span>{breakdown['Total']}W</span></div></div></div>"""
    return html

# --- SHARE MENU ---
@st.dialog("📤 Share Your Build")
def show_share_menu(link):
    st.write("Choose a platform:")
    st.text_input("Copy Link:", value=link)
    col1, col2 = st.columns(2)
    col3, col4 = st.columns(2)
    btn_style = """<style>.share-btn { display: inline-block; text-decoration: none; color: white !important; width: 100%; padding: 10px; text-align: center; border-radius: 8px; font-weight: bold; margin-bottom: 10px; }</style>"""
    st.markdown(btn_style, unsafe_allow_html=True)
    with col1: st.markdown(f'<a href="https://www.facebook.com/sharer/sharer.php?u={link}" target="_blank" class="share-btn" style="background-color: #1877F2;">📘 Facebook</a>', unsafe_allow_html=True)
    with col2: st.markdown(f'<a href="https://api.whatsapp.com/send?text=Check%20out%20this%20PC:%20{link}" target="_blank" class="share-btn" style="background-color: #25D366;">💬 WhatsApp</a>', unsafe_allow_html=True)
    with col3: st.markdown(f'<a href="fb-messenger://share/?link={link}" target="_blank" class="share-btn" style="background-color: #0084FF;">⚡ Messenger</a>', unsafe_allow_html=True)
    with col4: st.markdown(f'<a href="mailto:?subject=My PC Build&body=Check out this build: {link}" class="share-btn" style="background-color: #555;">✉️ Email</a>', unsafe_allow_html=True)

# --- MASTER BUILD LOGIC ---
def generate_pc_build(budget, include_gpu=True, fixed_cpu=None):
    conn = get_db_connection()
    if not conn: return None, 0, 0, 0, False, None
    cursor = conn.cursor()
    remaining = budget
    parts = {}
    
    # --- PHASE 1: CPU ---
    cpu = None
    if fixed_cpu:
        cpu = fixed_cpu
    else:
        cpu = get_best_item(cursor, "processors", budget * 0.30) or get_cheapest_item(cursor, "processors")

    if cpu: 
        if remaining - cpu['price'] < 5000:
            return None, 0, 0, 0, False, None
        remaining -= cpu['price']
        parts['CPU'] = dict(cpu)
        
        cpu_name = cpu['name'].upper()
        if "INTEL" in cpu_name: cpu_type = "Intel"
        elif "AMD" in cpu_name: cpu_type = "AMD"
        else: cpu_type = None
        gpu_required = is_gpu_mandatory(cpu['name'])
        
        # --- PHASE 2: BUDGET ALLOCATION ---
        cash_left = remaining
        
        # Squeeze Logic: If cash is low (<45k) but GPU is needed
        mobo_alloc = 0.20
        ram_alloc = 0.10
        ssd_alloc = 0.10
        
        # If CPU is expensive but budget is tight, squeeze harder
        should_buy_gpu = include_gpu or gpu_required
        if should_buy_gpu and cash_left < 45000:
             mobo_alloc = 0.25 # Lower allocation (relative to cash_left)
             ram_alloc = 0.10
             ssd_alloc = 0.10
        
        if fixed_cpu:
            mobo_budget = cash_left * mobo_alloc
            ram_budget = cash_left * ram_alloc
            ssd_budget = cash_left * ssd_alloc
        else:
            mobo_budget = budget * 0.20
            ram_budget = budget * 0.10
            ssd_budget = budget * 0.10

        # --- MOTHERBOARD & RAM ---
        mobo = None
        if cpu_type: mobo = get_best_item(cursor, "motherboards", mobo_budget, cpu_type)
        if not mobo: mobo = get_best_item(cursor, "motherboards", mobo_budget) or get_cheapest_item(cursor, "motherboards")
            
        if mobo:
            remaining -= mobo['price']
            parts['Motherboard'] = dict(mobo)
            mobo_name = mobo['name'].upper()
            ram_type = "DDR4"
            if "DDR5" in mobo_name or " D5 " in mobo_name or any(x in mobo_name for x in ["X670", "B650", "AM5", "Z790", "A620"]):
                if "D4" not in mobo_name: ram_type = "DDR5"
            
            ram = get_best_item(cursor, "rams", ram_budget, ram_type) or get_best_item(cursor, "rams", ram_budget, "DDR4") or get_cheapest_item(cursor, "rams")
            if ram: remaining -= ram['price']; parts['RAM'] = dict(ram)
    
    # --- PHASE 3: STORAGE & CASING ---
    ssd = get_best_item(cursor, "ssds", ssd_budget) or get_cheapest_item(cursor, "ssds")
    if ssd: remaining -= ssd['price']; parts['Storage'] = dict(ssd)
    
    casing = get_best_item(cursor, "casings", 5000) or get_cheapest_item(cursor, "casings")
    if casing: remaining -= casing['price']; parts['Casing'] = dict(casing)

    # --- PHASE 4: GPU & PSU ---
    advice_msg = None # Stores the advice for the user

    if should_buy_gpu:
        if budget < 60000: psu_reserve = 3500 
        elif budget < 100000: psu_reserve = 5000 
        else: psu_reserve = budget * 0.10

        gpu = None
        gpu_budget = remaining - psu_reserve 
        
        # THE ADVISOR LOGIC 💡
        # If we have money for ANY GPU, we buy it first.
        if gpu_budget > 5000:
            gpu = get_best_item(cursor, "gpus", gpu_budget)
            if gpu: 
                remaining -= gpu['price']
                parts['Graphics Card'] = dict(gpu)
                
                # Check for severe imbalance
                if gpu['price'] < (parts['CPU']['price'] * 0.5):
                    needed = int((parts['CPU']['price'] * 0.8) - gpu['price'])
                    advice_msg = f"💡 **Advisor:** This GPU is weak for your CPU. Consider **increasing budget by {needed} BDT** for a balanced card."
                    if not gpu_required:
                         advice_msg += " OR **Uncheck 'Include GPU'** to use Integrated Graphics and save for later."

        else:
            # We CANNOT afford a GPU.
            if gpu_required:
                needed = 15000 - gpu_budget # Aim for at least 15k
                advice_msg = f"❌ **Budget Crisis:** Cannot afford a dedicated GPU for this CPU! **Please add ~{int(needed)} BDT** to your budget."
            else:
                advice_msg = "💡 **Advisor:** Budget is too tight for a decent GPU. We skipped it. Use the CPU's Integrated Graphics and save up!"

    breakdown_data = calculate_power_breakdown(parts) 
    estimated_watts = breakdown_data['Total']
    recommended_psu_watts = estimated_watts + 150 
    
    psu = get_best_item(cursor, "psus", remaining, min_watts=recommended_psu_watts)
    if not psu: psu = get_cheapest_item(cursor, "psus", min_watts=recommended_psu_watts)
    if not psu: psu = get_best_item(cursor, "psus", remaining) 
    if psu: remaining -= psu['price']; parts['Power Supply'] = dict(psu)

    # --- PHASE 5: SWEEPER ---
    if should_buy_gpu:
        upgrade_order = [('Graphics Card', 'gpus', None), ('RAM', 'rams', ram_type), ('Storage', 'ssds', None)]
        if not fixed_cpu:
            upgrade_order.insert(1, ('CPU', 'processors', None)) 
            
        for part_name, table, constraint in upgrade_order:
            if part_name in parts and remaining > 1000:
                current_item = parts[part_name]
                current_price = current_item['price']
                potential_budget = current_price + remaining
                better_item = get_best_item(cursor, table, potential_budget, constraint)
                if better_item and better_item['price'] > current_price:
                    cost_diff = better_item['price'] - current_price
                    parts[part_name] = dict(better_item)
                    remaining -= cost_diff

    final_breakdown = calculate_power_breakdown(parts)
    conn.close()
    return parts, sum(p['price'] for p in parts.values()), remaining, final_breakdown, gpu_required, advice_msg

# --- UI START ---
st.title("🖥️ BD PC Builder AI v9.1")
st.caption("Smart Advisor. Budget Crisis Detection.")

query_params = st.query_params
safe_budget = 40000
if "budget" in query_params:
    try: safe_budget = int(query_params["budget"])
    except: pass

with st.container():
    col1, col2 = st.columns([1, 1])
    with col1:
        budget_input = st.number_input("💰 Budget (BDT)", min_value=15000, max_value=800000, step=1000, value=safe_budget, key="budget_v9")
    with col2:
        cpu_choice_mode = st.radio("CPU Selection:", ["🤖 AI Decides", "🎯 I Choose"], horizontal=True)

    selected_cpu_obj = None
    is_locked = False
    
    if cpu_choice_mode == "🎯 I Choose":
        all_cpus = get_all_cpus()
        cpu_selection = st.selectbox("Select your Processor:", all_cpus, help="The AI will build the rest of the PC around this CPU.")
        if cpu_selection:
            selected_cpu_obj = get_cpu_object(cpu_selection)
            if selected_cpu_obj and is_gpu_mandatory(selected_cpu_obj['name']):
                is_locked = True
                st.info(f"🔒 **Locked:** {selected_cpu_obj['name']} requires a Graphics Card.")

    if is_locked:
        include_gpu_check = st.checkbox("Include Graphics Card?", value=True, disabled=True, help="This CPU requires a GPU to display video.")
    else:
        include_gpu_check = st.checkbox("Include Graphics Card?", value=True)

if "build_results" not in st.session_state: st.session_state.build_results = None

if st.button("🚀 Build PC", type="primary", use_container_width=True):
    st.query_params["budget"] = budget_input
    
    parts, total_cost, saved, watts, gpu_forced, advice = generate_pc_build(budget_input, include_gpu_check, fixed_cpu=selected_cpu_obj)
    
    if parts is None:
        st.error(f"❌ Impossible Build! The CPU you selected costs more than your entire budget. Please increase budget.")
    else:
        st.session_state.build_results = {"parts": parts, "total": total_cost, "saved": saved, "watts": watts, "gpu_forced": gpu_forced, "advice": advice}

if st.session_state.build_results:
    data = st.session_state.build_results
    parts = data["parts"]
    current_total = sum(p['price'] for p in parts.values())
    current_breakdown = calculate_power_breakdown(parts)
    
    if parts:
        st.divider()
        # --- SMART ADVICE SECTION ---
        if data.get("advice"):
             # If it's a Crisis/Warning
             if "Crisis" in data["advice"] or "Bottleneck" in data["advice"]:
                 st.error(data["advice"])
             else:
                 st.info(data["advice"])
                 
        if data.get("gpu_forced") and not is_locked:
             st.warning("⚠️ GPU was added automatically because the AI selected a CPU without Integrated Graphics.")
             
        col_res1, col_res2, col_res3 = st.columns([2, 1, 1])
        with col_res1: st.success(f"✅ Total: **{current_total} BDT**")
        with col_res2:
             share_url = f"https://bd-pc-builder.streamlit.app/?budget={budget_input}"
             if st.button("📤 Share", use_container_width=True): show_share_menu(share_url)  
        with col_res3:
            badge_html = render_power_badge(current_breakdown)
            st.markdown(badge_html, unsafe_allow_html=True)
            
        with st.expander("📋 View & Copy Parts List"):
            summary_text = generate_build_summary(parts, current_total, current_breakdown['Total'])
            st.code(summary_text, language="text")

        st.divider()

        # --- SEPARATE REQUIRED VS OPTIONAL ---
        st.subheader("🛠️ Core Components")
        core_items = {k: v for k, v in parts.items() if k != 'Graphics Card'}
        gpu_item = parts.get('Graphics Card')

        table_map = {
            'CPU': 'processors', 'Motherboard': 'motherboards', 'RAM': 'rams',
            'Storage': 'ssds', 'Graphics Card': 'gpus', 'Power Supply': 'psus', 'Casing': 'casings'
        }

        for part_type, item in core_items.items():
            with st.container():
                col_img, col_details, col_price, col_action = st.columns([1, 2, 1, 0.5])
                with col_img:
                    if item.get('image_url'): st.image(item['image_url'], width=80)
                    else: st.write("📦")
                with col_details:
                    st.markdown(f"**{part_type}**")
                    st.caption(item['name'])
                    if part_type == "Power Supply":
                         watts = get_wattage(item['name'])
                         if watts > 0: st.caption(f"⚡ Capacity: {watts}W")
                with col_price:
                    st.markdown(f"**{item['price']} ৳**")
                    if item.get('url'): st.link_button("🛒", f"{item['url']}?ref=YOUR_ID")
                with col_action:
                    # DISABLE SWAP FOR CPU IF USER FIXED IT
                    if part_type == 'CPU' and cpu_choice_mode == "🎯 I Choose":
                        st.write("🔒") 
                    else:
                        constraint = None
                        if part_type == 'CPU': 
                            if "INTEL" in item['name'].upper(): constraint = "Intel"
                            elif "AMD" in item['name'].upper() or "RYZEN" in item['name'].upper(): constraint = "AMD"
                        elif part_type == 'Motherboard':
                            cpu_name = parts['CPU']['name'].upper()
                            if "INTEL" in cpu_name: constraint = "Intel"
                            elif "AMD" in cpu_name or "RYZEN" in cpu_name: constraint = "AMD" 
                        elif part_type == 'RAM':
                            constraint = "DDR5" if "DDR5" in parts['Motherboard']['name'].upper() else "DDR4"
                        
                        with st.popover("🔄"):
                            st.markdown(f"**Swap {part_type}**")
                            table_name = table_map.get(part_type)
                            if table_name:
                                alts = get_alternatives(table_name, item['price'], constraint)
                                alts.insert(0, item) 
                                seen = set()
                                unique_alts = []
                                for a in alts:
                                    if a['name'] not in seen: unique_alts.append(a); seen.add(a['name'])

                                if unique_alts:
                                    alt_map = {f"{a['name'][:40]}... ({a['price']} ৳)": a for a in unique_alts}
                                    selected_name = st.selectbox("Choose:", list(alt_map.keys()), index=0, key=f"sel_{part_type}")
                                    if st.button("Confirm", key=f"btn_{part_type}"):
                                        st.session_state.build_results['parts'][part_type] = alt_map[selected_name]
                                        st.rerun()

        if gpu_item:
            st.subheader("🎮 Graphics & Expansion")
            with st.container():
                col_img, col_details, col_price, col_action = st.columns([1, 2, 1, 0.5])
                with col_img:
                    if gpu_item.get('image_url'): st.image(gpu_item['image_url'], width=80)
                    else: st.write("📦")
                with col_details:
                    st.markdown("**Graphics Card**")
                    st.caption(gpu_item['name'])
                with col_price:
                    st.markdown(f"**{gpu_item['price']} ৳**")
                    if gpu_item.get('url'): st.link_button("🛒", f"{gpu_item['url']}?ref=YOUR_ID")
                with col_action:
                    with st.popover("🔄"):
                        st.markdown("**Swap GPU**")
                        alts = get_alternatives("gpus", gpu_item['price'])
                        alts.insert(0, gpu_item)
                        seen = set()
                        unique_alts = []
                        for a in alts:
                            if a['name'] not in seen: unique_alts.append(a); seen.add(a['name'])
                        
                        alt_map = {f"{a['name'][:40]}... ({a['price']} ৳)": a for a in unique_alts}
                        selected_name = st.selectbox("Choose:", list(alt_map.keys()), index=0, key="sel_gpu")
                        if st.button("Confirm", key="btn_gpu"):
                            st.session_state.build_results['parts']['Graphics Card'] = alt_map[selected_name]
                            st.rerun()

                st.divider()

        live_unused = budget_input - current_total
        if live_unused > 20000:
            st.info(f"💎 **Surplus Budget: {live_unused} BDT**\n\nYou have purchased the best available components! Use this extra cash for a Monitor, Keyboard, or specialized cooling.")
        elif live_unused > 0:
            st.warning(f"💵 Unused Budget: {live_unused} BDT")
        elif live_unused < 0:
            st.error(f"⚠️ Over Budget: {abs(live_unused)} BDT")